### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by jerryakpera** [jta11developer/github-crash-course#1]
I think it will look better if the main title is a bit more orage.

The styling rule could be changed like this:

```css
h1 {
  color: #c4923c;
}
```
